package cas.Sorting;

public enum Weather_Type_Enum {
	Astronomical_Low_Tide, 
	Avalanche, 
	Blizzard, 
	Coastal_Flood, 
	Cold_Wind_Chill, 
	Debris_Flow, 
	Dense_Fog, 
    Dense_Smoke, 
    Drought, 
    Dust_Devil, 
    Dust_Storm, 
    Excessive_Heat, 
    Extreme_Cold_Wind_Chill, 
    Flash_Flood, 
    //Flood,//issue with enum type
    Frost_Freeze,
    Funnel_Cloud, 
    Freezing_Fog, 
    //Hail, 
    Heat, 
    Heavy_Rain, 
    Heavy_Snow, 
    High_Surf, 
    High_Wind, 
    Hurricane_Typhoon_,
    Ice_Storm, 
    Lake_Effect_Snow, 
    Lake_shore_Flood,
    //Lighting, 
    Marine_Hail, 
    Marine_High_Wind, 
    Marine_Strong_Wind, 
    Marine_Thunder_Wind, 
    Rip_Current, 
    Seiche, 
    Sleet, 
    Storm_Surge_Tide, 
    Strong_Wind, 
    Thunderstorm_Wind, 
    Tornado, 
    Tropical_Depression, 
    Tropical_Storm,
    Tsunami, 
    Volcanic_Ash, 
    Waterspout , 
    Wildfire, 
    Winter_Storm, 
    Winter_Weather 
}
